#!/bin/bash
set -euo pipefail

npm install git+https://github.com/yuvipanda/visualizer

pip install -U git+https://github.com/yuvipanda/nbserverproxy.git@no-host

curl -L "https://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.6&type=binary&os=Linux&downloadFile=ParaView-5.6.0-MPI-Linux-64bit.tar.gz" | tar -xvzf -

cp jupyter_notebook_config.py $HOME/.jupyter
